theme: jekyll-theme-minimal
title: Кириллический шрифт «18 век»
description: Декоративная антиква в типографской стилистике XVIII века
logo: logo.png
show_downloads: true
google_analytics: UA-2442526-2
